language: php

php:
  - 7.0

before_script:
  - composer global require "squizlabs/php_codesniffer=*"
  - composer global config bin-dir --absolute
  - composer global install
  - phpenv rehash
  - git clone --depth 1 git://github.com/laravel/laravel ../laravel
  - cd ../laravel
  - composer install
  - git clone git://github.com/It-Quattro/El-Gringo-Library ../El-Gringo
  - cp -rf ../El-Gringo/* ./
  - chmod -R 777 ./storage
  - chmod -R 777 ./bootstrap/cache
  - sh -c "mysql -e 'CREATE DATABASE library_test;'"
  - cp -rf ../El-Gringo/.env.testing ./.env
  - echo "<?php
            return [
                'default' => env('DB_CONNECTION', 'mysql'),
                'connections' => [
                    'mysql' => [
                        'driver' => 'mysql',
                        'host' => env('DB_HOST', '127.0.0.1'),
                        'port' => env('DB_PORT', '3306'),
                        'database' => env('DB_DATABASE', 'library'),
                        'username' => env('DB_USERNAME', 'root'),
                        'password' => env('DB_PASSWORD', '0000'),
                        'unix_socket' => env('DB_SOCKET', ''),
                        'charset' => 'utf8mb4',
                        'collation' => 'utf8mb4_unicode_ci',
                        'prefix' => '',
                        'strict' => true,
                        'engine' => null,
                    ]
                ],
                'migrations' => 'migrations',
                'redis' => [

                    'client' => 'predis',

                    'default' => [
                        'host' => env('REDIS_HOST', '127.0.0.1'),
                        'password' => env('REDIS_PASSWORD', null),
                        'port' => env('REDIS_PORT', 6379),
                        'database' => 0,
                    ],

                ],

            ];" > ./config/database.php
  - git clone git://github.com/antonioribeiro/laravelcs ../codeSniffer

script:
  - ./vendor/bin/phpunit
  - phpcs --standard=../codeSniffer/Standards/Laravel/ ./app/Http/Controllers/



